services:
  db:
    image: postgres:15-alpine
    container_name: macromeals_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      # - "5432:5432"
      - "5434:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  #application layer
  backend:
    build:
      context: ./application
    container_name: macromeals_backend
    entrypoint: /app/entrypoint.sh
    command: python application/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DEBUG=1
      - DB_HOST=db
      - DB_PORT=${DB_PORT}
      - DB_NAME=${POSTGRES_DB}
      - DB_USER=${POSTGRES_USER}
      - DB_PASS=${POSTGRES_PASSWORD}
      - PYTHONUNBUFFERED=1
      - USDA_API_KEY=${USDA_API_KEY}
  # presentation layer (frontend)
  frontend:
    build:
      context: ./presentation
      target: development-dependencies-env
    container_name: macromeals_frontend
    volumes:
      - ./presentation:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    command: npm run dev
    environment:
      - SERVER_URL=${SERVER_URL}
      - APP_SECRET=${APP_SECRET}
      - NODE_ENV=${NODE_ENV}

volumes:
  postgres_data:
