# Generated by Django 6.0.2 on 2026-03-01 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='carbsGoal',
            new_name='carbs_goal',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='dailyCalorieGoal',
            new_name='daily_calorie_goal',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='fatGoal',
            new_name='fat_goal',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='proteinGoal',
            new_name='protein_goal',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='waterGoal',
            new_name='water_goal',
        ),
    ]
