# Generated by Django 6.0.2 on 2026-03-05 03:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_carbsgoal_customuser_carbs_goal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='water_goal',
            field=models.PositiveIntegerField(blank=True, default=25, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
