# Generated by Django 6.0.2 on 2026-03-05 16:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_water_goal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='water_goal',
            field=models.PositiveIntegerField(blank=True, default=2500, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
