# Generated by Django 6.0.2 on 2026-03-19 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_customuser_age_customuser_biological_sex_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="age",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="biological_sex",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="height_cm",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="onboarding_complete",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="weight_kg",
        ),
    ]
