# Generated by Django 6.0.2 on 2026-03-07 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_customuser_water_goal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='water_goal',
            field=models.DecimalField(blank=True, decimal_places=1, default=2.5, max_digits=3, null=True),
        ),
    ]
