# Generated by Django 6.0.2 on 2026-03-25 21:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_alter_customuser_biological_sex_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="biological_sex",
            field=models.CharField(
                blank=True,
                choices=[
                    ("male", "Male"),
                    ("female", "Female"),
                    ("other", "Other / Prefer not to say"),
                ],
                help_text="Used only for BMR calculation (Mifflin-St Jeor equation)",
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="height_cm",
            field=models.FloatField(
                blank=True,
                help_text="Height in centimetres",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(50),
                    django.core.validators.MaxValueValidator(280),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="onboarding_complete",
            field=models.BooleanField(
                default=False,
                help_text="True once the user has completed the initial goals quiz",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="weight_kg",
            field=models.FloatField(
                blank=True,
                help_text="Weight in kilograms",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(20),
                    django.core.validators.MaxValueValidator(500),
                ],
            ),
        ),
        migrations.DeleteModel(
            name="FriendRequest",
        ),
    ]
