# Generated by Django 6.0.2 on 2026-03-30 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_alter_customuser_biological_sex_and_more"),
        ("accounts", "0007_alter_customuser_biological_sex_and_more"),
    ]

    operations = []
