# Generated by Django 6.0.2 on 2026-03-31 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_customuser_age_customuser_biological_sex_and_more"),
        ("accounts", "0008_merge_20260330_2340"),
    ]

    operations = []
