# Generated by Django 6.0.2 on 2026-02-27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipeingredient",
            name="calories_per_100g",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="recipeingredient",
            name="carbs_per_100g",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="recipeingredient",
            name="fat_per_100g",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="recipeingredient",
            name="protein_per_100g",
            field=models.FloatField(default=0),
        ),
    ]
