# Generated by Django 6.0.2 on 2026-03-24 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0002_recipeingredient_macro_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="recipe_image",
            field=models.TextField(blank=True, default="vv"),
        ),
    ]
