# Generated by Django 6.0.2 on 2026-03-20 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0002_recipeingredient_macro_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="is_public",
            field=models.BooleanField(
                default=False,
                help_text="When True, this recipe is visible to all other users on the Community page.",
            ),
        ),
        migrations.AddField(
            model_name="recipe",
            name="source_recipe",
            field=models.ForeignKey(
                blank=True,
                help_text="The original public recipe this was copied from, if any.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="copies",
                to="recipes.recipe",
            ),
        ),
    ]
