# Generated by Django 6.0.2 on 2026-03-31 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0003_recipe_is_public_recipe_source_recipe"),
        ("recipes", "0003_recipe_recipe_image"),
    ]

    operations = []
