# Generated by Django 6.0.2 on 2026-03-29 23:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0003_recipe_recipe_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recipe",
            name="recipe_image",
        ),
        migrations.AddField(
            model_name="recipe",
            name="source_recipe",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="copies",
                to="recipes.recipe",
            ),
        ),
        migrations.AddField(
            model_name="recipe",
            name="visibility",
            field=models.CharField(
                choices=[
                    ("private", "Private"),
                    ("friends_only", "Friends Only"),
                    ("public", "Public"),
                ],
                default="private",
                help_text="private = only you | friends_only = accepted friends | public = everyone",
                max_length=15,
            ),
        ),
    ]
