# Generated by Django 6.0.2 on 2026-03-25 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0004_remove_recipe_is_public_recipe_visibility_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recipe",
            name="source_recipe",
        ),
        migrations.RemoveField(
            model_name="recipe",
            name="visibility",
        ),
        migrations.AddField(
            model_name="recipe",
            name="recipe_image",
            field=models.TextField(blank=True, default="vv"),
        ),
    ]
