# Generated by Django 6.0.2 on 2026-03-09 02:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal_logs', '0003_meallog_servings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meallog',
            options={'ordering': ['-date_logged', '-created_at']},
        ),
        migrations.AddField(
            model_name='meallog',
            name='date_logged',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='meallog',
            name='meal_name',
            field=models.CharField(choices=[('BREAKFAST', 'Breakfast'), ('LUNCH', 'Lunch'), ('DINNER', 'Dinner'), ('SNACK', 'Snack')], max_length=20),
        ),
    ]
