# Generated by Django 6.0.2 on 2026-03-14 00:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meal_logs", "0005_waterlog"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="waterlog",
            options={"ordering": ["-date_logged", "-created_at"]},
        ),
        migrations.AddField(
            model_name="waterlog",
            name="date_logged",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
