# Generated by Django 6.0.2 on 2026-03-31 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("meal_logs", "0006_alter_waterlog_options_waterlog_date_logged"),
        ("meal_logs", "0006_meallog_recipe_name"),
    ]

    operations = []
