# Generated by Django 6.0.2 on 2026-03-29 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meal_logs", "0006_alter_waterlog_options_waterlog_date_logged"),
    ]

    operations = [
        migrations.AddField(
            model_name="meallog",
            name="recipe_name",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
    ]
