# Generated by Django 6.0.2 on 2026-03-29 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meal_logs", "0007_meallog_recipe_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meallog",
            name="recipe_name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
